---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: debian-7.8
  - name: fedora-21
  - name: ubuntu-14.10
  - name: freebsd-10.1

suites:
  - name: default
    run_list:
      - recipe[btsync::default]
    attributes:
